//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Groupe HBF")]
[assembly: System.Reflection.AssemblyProduct("OtioHome")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Groupe HBF 2021")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0")]
[assembly: System.Reflection.AssemblyVersion("2.0.0")]
[assembly: System.Reflection.AssemblyTitle("Symbiot.Mobile.Android")]


