// <auto-generated/>
// https://gist.githubusercontent.com/Char0394/1bd09f9a450b214946ed17dbee7294af/raw/eb4ba5d6c27bcac935b8e1bf3008d9d6594e3841/NullableDatePickerRenderer.cs

using System;
using System.Collections.Generic;

using Symbiot.Mobile.iOS.Renderers;
using Symbiot.Mobile.Presentation.CustomViews;

using UIKit;

using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(NullableDatePicker), typeof(NullableDatePickerRenderer))]
namespace Symbiot.Mobile.iOS.Renderers
{
    public class NullableDatePickerRenderer : DatePickerRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null && this.Control != null)
            {
                this.AddClearButton();

                this.Control.BorderStyle = UITextBorderStyle.Line;
                Control.Layer.BorderColor = UIColor.LightGray.CGColor;
                Control.Layer.BorderWidth = 1;

                if (Device.Idiom == TargetIdiom.Tablet)
                {
                    this.Control.Font = UIFont.SystemFontOfSize(25);
                }
            }

        }

        private void AddClearButton()
        {
            if (this.Control.InputAccessoryView is UIToolbar originalToolbar && originalToolbar.Items.Length <= 2)
            {
                var clearButton = new UIBarButtonItem(
                    "Clear",
                    UIBarButtonItemStyle.Plain,
                    (sender, ev) =>
                        {
                            var baseDatePicker = (NullableDatePicker)this.Element;
                            this.Element.Unfocus();
                            this.Element.Date = DateTime.Now;
                            baseDatePicker.CleanDate();

                        });

                var newItems = new List<UIBarButtonItem>();
                foreach (var item in originalToolbar.Items)
                {
                    newItems.Add(item);
                }

                newItems.Insert(0, clearButton);

                originalToolbar.Items = newItems.ToArray();
                originalToolbar.SetNeedsDisplay();
            }

        }
    }
}