//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symbiot.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symbiot.Mobile.Localization.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement....
        /// </summary>
        internal static string Common_Saving {
            get {
                return ResourceManager.GetString("Common_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous n&apos;arrivons pas à joindre notre serveur.
        ///Veuillez vérifier votre connexion..
        /// </summary>
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande n&apos;a pas pu être traitée.
        ///Veuillez vérifier les informations saisies..
        /// </summary>
        internal static string Error_Server_Business {
            get {
                return ResourceManager.GetString("Error_Server_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le serveur a rencontré une erreur technique.
        ///Nous travaillons sur le problème..
        /// </summary>
        internal static string Error_Server_Technical {
            get {
                return ResourceManager.GetString("Error_Server_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande n&apos;a pas pu être traitée,
        ///Code erreur : {0}.
        /// </summary>
        internal static string Error_Server_Unknown {
            get {
                return ResourceManager.GetString("Error_Server_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur inconnue s&apos;est produite.
        ///Merci de réessayer ultérieurement..
        /// </summary>
        internal static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité.
        /// </summary>
        internal static string Section_Activities_TabText {
            get {
                return ResourceManager.GetString("Section_Activities_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité.
        /// </summary>
        internal static string Section_Activities_Title {
            get {
                return ResourceManager.GetString("Section_Activities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-shop.
        /// </summary>
        internal static string Section_EShop_TabText {
            get {
                return ResourceManager.GetString("Section_EShop_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-shop.
        /// </summary>
        internal static string Section_EShop_Title {
            get {
                return ResourceManager.GetString("Section_EShop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicile.
        /// </summary>
        internal static string Section_Home_TabText {
            get {
                return ResourceManager.GetString("Section_Home_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicile.
        /// </summary>
        internal static string Section_Home_Title {
            get {
                return ResourceManager.GetString("Section_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scénarios.
        /// </summary>
        internal static string Section_Scenarios_TabText {
            get {
                return ResourceManager.GetString("Section_Scenarios_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scénarios.
        /// </summary>
        internal static string Section_Scenarios_Title {
            get {
                return ResourceManager.GetString("Section_Scenarios_Title", resourceCulture);
            }
        }
    }
}
