//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvvm.Flux.Maui.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mvvm.Flux.Maui.Localization.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        internal static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        internal static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        internal static string Common_Saving {
            get {
                return ResourceManager.GetString("Common_Saving", resourceCulture);
            }
        }
        
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        internal static string Error_Server_Business {
            get {
                return ResourceManager.GetString("Error_Server_Business", resourceCulture);
            }
        }
        
        internal static string Error_Server_Technical {
            get {
                return ResourceManager.GetString("Error_Server_Technical", resourceCulture);
            }
        }
        
        internal static string Error_Server_Unknown {
            get {
                return ResourceManager.GetString("Error_Server_Unknown", resourceCulture);
            }
        }
        
        internal static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        internal static string Section_Activities_TabText {
            get {
                return ResourceManager.GetString("Section_Activities_TabText", resourceCulture);
            }
        }
        
        internal static string Section_Activities_Title {
            get {
                return ResourceManager.GetString("Section_Activities_Title", resourceCulture);
            }
        }
        
        internal static string Section_EShop_TabText {
            get {
                return ResourceManager.GetString("Section_EShop_TabText", resourceCulture);
            }
        }
        
        internal static string Section_EShop_Title {
            get {
                return ResourceManager.GetString("Section_EShop_Title", resourceCulture);
            }
        }
        
        internal static string Section_Home_TabText {
            get {
                return ResourceManager.GetString("Section_Home_TabText", resourceCulture);
            }
        }
        
        internal static string Section_Home_Title {
            get {
                return ResourceManager.GetString("Section_Home_Title", resourceCulture);
            }
        }
        
        internal static string Section_Scenarios_TabText {
            get {
                return ResourceManager.GetString("Section_Scenarios_TabText", resourceCulture);
            }
        }
        
        internal static string Section_Scenarios_Title {
            get {
                return ResourceManager.GetString("Section_Scenarios_Title", resourceCulture);
            }
        }
    }
}
